# Generated by Django 5.1.1 on 2024-09-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cultura', models.CharField(max_length=120)),
                ('regiao', models.CharField(max_length=120)),
                ('tema', models.CharField(max_length=120)),
                ('idioma', models.CharField(max_length=120)),
                ('conteudo', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
